included:
  - App/xcbuddykit/Sources
  - App/Sources
excluded:
  - Sources
  - Tests
  - .build
disabled_rules:
  - trailing_whitespace
  - nesting
  - cyclomatic_complexity
  - file_length
  - todo
line_length:
  warning: 150
  error: 170
