version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-{{ .Branch }}
            - gem-cache
      - restore_cache:
          keys:
            - swift-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Package.resolved" }}
            - swift-cache-{{ arch }}-{{ .Branch }}
            - swift-cache
      - restore_cache:
          keys:
            - xcode-cache-{{ arch }}-{{ .Branch }}
      - run:
          name: Install Dependencies
          command: |
            bundle config build.sqlite3 --with-sqlite3-dir=/opt/local
            brew install swiftlint
            bundle install --path vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rake test
      - run:
          name: Danger
          command: bundle exec danger
      - run:
          name: Send test coverage report
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: swift-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Package.resolved" }}
          paths:
            - .build/
      - save_cache:
          key: xcode-cache-{{ arch }}-{{ .Branch }}
          paths:
            - ~/Library/Developer/Xcode/DerivedData


                
